apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
spec:
  type: NodePort
  ports:
    - name: 8080-tcp
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ui
